#ifndef VERSION_HPP
#define VERSION_HPP

#define THERMALCAMERA_VERSION_MAJOR 1
#define THERMALCAMERA_VERSION_MINOR 0
#define THERMALCAMERA_VERSION_PATCH 0
#define THERMALCAMERA_VERSION_STRING "1.0.0"

#endif // VERSION_HPP
